import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration for the revealjs_editor extension.
 *
 * Setup model:
 *   - Tests run **inside DDEV** via the `ochorocho/ddev-playwright` add-on
 *     (installed under `.ddev/docker-compose.playwright.yaml`). The add-on
 *     adds a sidecar `playwright` service running the official Microsoft
 *     Playwright Docker image (pinned to v1.59.0 in `.ddev/.env.playwright`,
 *     matching the host's `@playwright/test`).
 *
 *   - The Playwright container links to the `web` service, so tests reach
 *     the TYPO3 install at the internal docker-network hostname `http://web`
 *     — no HTTPS, no DDEV traefik in the path. Override via
 *     `PLAYWRIGHT_BASE_URL` to point at any other endpoint.
 *
 *   - **Two databases, header-routed.** The editor reads/writes `db`; tests
 *     read/write `test`. Both are TYPO3 installs against the same `web`
 *     service — what differentiates them is the `X-Test-Run: 1` header that
 *     `extraHTTPHeaders` below sets on every Playwright request. The TYPO3
 *     bootstrap (`Build/config/system/additional.php`, generated by
 *     setup-typo3.sh) sees that header and swaps the active connection's
 *     dbname to `test` before any query runs. Editor's browser doesn't send
 *     the header → keeps reading `db`.
 *
 *   - **test database is reseeded before every run.** `globalSetup` below
 *     points at `Tests/playwright/scripts/global-setup.mjs`, which runs
 *     once per `ddev playwright test` invocation and TRUNCATE-imports the
 *     CSV fixtures into `test`. Tests can freely mutate `test` (BE form
 *     saves, write-tests, etc.) — the next run wipes the slate clean.
 *
 *   - **DB fixture (`dbConfig`).** Wires the knex-backed `db` Playwright
 *     fixture from `@ochorocho/playwright-db-connector` against the SAME
 *     `test` database the SUT is served from. Specs that import `test` /
 *     `expect` from that package get the `seeInDatabase()` /
 *     `haveInDatabase()` API. `cleanupStrategy: 'transaction'` rolls back
 *     fixture writes at teardown, but TYPO3 BE form saves use TYPO3's own
 *     connection (outside the transaction) — those persist in `test` until
 *     the next globalSetup reset.
 *
 * Run:
 *   npm install                          # one-off (installs deps)
 *   ddev add-on get ochorocho/ddev-playwright  # one-off
 *   ddev restart                         # bring up the playwright sidecar;
 *                                        # setup-typo3.sh provisions both
 *                                        # db (editor) and test (Playwright).
 *   ddev playwright test                 # globalSetup reseeds `test`, then runs all specs
 *   ddev playwright browser              # interactive UI mode
 *   ddev playwright show-report          # last HTML report
 */
export default defineConfig({
    testDir: './Tests/playwright/specs',
    globalSetup: './Tests/playwright/scripts/global-setup.mjs',
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 1 : undefined,
    reporter: [['list'], ['html', { open: 'never' }]],
    timeout: 30_000,
    expect: { timeout: 10_000 },

    use: {
        // Inside the addon's Playwright container, the TYPO3 web service is
        // reachable at the docker-network hostname `web` over plain HTTP.
        // Override with PLAYWRIGHT_BASE_URL when running against a deployed
        // environment from outside DDEV.
        baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://web',
        trace: 'on-first-retry',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure',

        // Routes every Playwright request to TYPO3's `test` database via the
        // additional.php swap. Applied to page navigation, subresources, XHR,
        // and Playwright's `request` API — unconditionally, no opt-in needed.
        extraHTTPHeaders: { 'X-Test-Run': '1' },

        // Knex-backed DB fixture. Specs that opt in by importing `test` from
        // `@ochorocho/playwright-db-connector` get a `db` argument they can
        // call `seeInDatabase()`, `haveInDatabase()`, etc. on; transaction
        // cleanup is the default. From inside the addon's Playwright
        // container, the DDEV `db` service is reachable at `db:3306`. The
        // value from `process.env.PLAYWRIGHT_DB_*` lets ad-hoc runs override.
        // TYPO3's primary key is `uid`, not `id` — the fixture needs that
        // hint for `haveInDatabase()` to return the right value.
        // The fixture targets `test` (matches what the SUT serves under the
        // X-Test-Run header), so seeInDatabase assertions are coherent with
        // what the page-under-test rendered.
        // @ts-expect-error — the type comes from the merged fixtures.
        dbConfig: {
            client: 'mysql2',
            connection: {
                host: process.env.PLAYWRIGHT_DB_HOST ?? 'db',
                port: Number(process.env.PLAYWRIGHT_DB_PORT ?? 3306),
                user: process.env.PLAYWRIGHT_DB_USER ?? 'db',
                password: process.env.PLAYWRIGHT_DB_PASSWORD ?? 'db',
                database: process.env.PLAYWRIGHT_DB_NAME ?? 'test',
            },
            primaryKeyColumn: 'uid',
            cleanupStrategy: 'transaction',
        },
    },

    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] },
        },
    ],
});
